server:
  port: 8087

#banner:
#  location: banner.txt
#
#output:
#  ansi:
#    enabled: always
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#
#jsa:
#  rabbitmq:
#    queue: jsa.queue.1
#
#spring:
#  jpa:
#    database: h2
#    hibernate:
#      dialect: org.hibernate.dialect.H2Dialect
#    ddl-auto: none
#    open-in-view: false

spring:
  banner:
    location: banner.txt
  output:
    ansi:
      enabled: always
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:h2:tcp://localhost:9091/mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    database: h2
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
    ddl-auto: create #automatic schema creation (enabled)
    open-in-view: false

jsa:
  rabbitmq:
    queue: jsa.queue.1